/* msg\dfsnotdet.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 80,77,68,70,83,58,32,84,104,101,32,80,105,99,111,77
  S001 db 69,77,32,100,111,101,115,32,110,111,116,32,115,117,112,112
  S002 db 111,114,116,32,68,70,83,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
