/* msg\pmnotdet.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 80,77,68,70,83,58,32,80,105,99,111,77,69,77,32,110
  S001 db 111,116,32,100,101,116,101,99,116,101,100,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
